/* This file was generated by SableCC (http://www.sablecc.org/). */

package repmp3.node;

import repmp3.analysis.*;

@SuppressWarnings("nls")
public final class AMetaLine extends PLine
{
    private TMetaTag _metaTag_;

    public AMetaLine()
    {
        // Constructor
    }

    public AMetaLine(
        @SuppressWarnings("hiding") TMetaTag _metaTag_)
    {
        // Constructor
        setMetaTag(_metaTag_);

    }

    @Override
    public Object clone()
    {
        return new AMetaLine(
            cloneNode(this._metaTag_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetaLine(this);
    }

    public TMetaTag getMetaTag()
    {
        return this._metaTag_;
    }

    public void setMetaTag(TMetaTag node)
    {
        if(this._metaTag_ != null)
        {
            this._metaTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metaTag_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metaTag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metaTag_ == child)
        {
            this._metaTag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metaTag_ == oldChild)
        {
            setMetaTag((TMetaTag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
