/* This file was generated by SableCC (http://www.sablecc.org/). */

package repmp3.node;

import repmp3.analysis.*;

@SuppressWarnings("nls")
public final class Start extends Node
{
    private PLrcFile _pLrcFile_;
    private EOF _eof_;

    public Start()
    {
        // Empty body
    }

    public Start(
        @SuppressWarnings("hiding") PLrcFile _pLrcFile_,
        @SuppressWarnings("hiding") EOF _eof_)
    {
        setPLrcFile(_pLrcFile_);
        setEOF(_eof_);
    }

    @Override
    public Object clone()
    {
        return new Start(
            cloneNode(this._pLrcFile_),
            cloneNode(this._eof_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PLrcFile getPLrcFile()
    {
        return this._pLrcFile_;
    }

    public void setPLrcFile(PLrcFile node)
    {
        if(this._pLrcFile_ != null)
        {
            this._pLrcFile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pLrcFile_ = node;
    }

    public EOF getEOF()
    {
        return this._eof_;
    }

    public void setEOF(EOF node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        if(this._pLrcFile_ == child)
        {
            this._pLrcFile_ = null;
            return;
        }

        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        if(this._pLrcFile_ == oldChild)
        {
            setPLrcFile((PLrcFile) newChild);
            return;
        }

        if(this._eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public String toString()
    {
        return "" +
            toString(this._pLrcFile_) +
            toString(this._eof_);
    }
}
