/* This file was generated by SableCC (http://www.sablecc.org/). */

package repmp3.node;

import repmp3.analysis.*;

@SuppressWarnings("nls")
public final class TMetaTag extends Token
{
    public TMetaTag(String text)
    {
        setText(text);
    }

    public TMetaTag(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMetaTag(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMetaTag(this);
    }
}
