/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea2.node;

import tarea2.analysis.*;

@SuppressWarnings("nls")
public final class ALyricLine extends PLine
{
    private TTimeTag _timeTag_;
    private TText _text_;

    public ALyricLine()
    {
        // Constructor
    }

    public ALyricLine(
        @SuppressWarnings("hiding") TTimeTag _timeTag_,
        @SuppressWarnings("hiding") TText _text_)
    {
        // Constructor
        setTimeTag(_timeTag_);

        setText(_text_);

    }

    @Override
    public Object clone()
    {
        return new ALyricLine(
            cloneNode(this._timeTag_),
            cloneNode(this._text_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALyricLine(this);
    }

    public TTimeTag getTimeTag()
    {
        return this._timeTag_;
    }

    public void setTimeTag(TTimeTag node)
    {
        if(this._timeTag_ != null)
        {
            this._timeTag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timeTag_ = node;
    }

    public TText getText()
    {
        return this._text_;
    }

    public void setText(TText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timeTag_)
            + toString(this._text_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timeTag_ == child)
        {
            this._timeTag_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timeTag_ == oldChild)
        {
            setTimeTag((TTimeTag) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((TText) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
