/* This file was generated by SableCC (http://www.sablecc.org/). */

package repmp3.analysis;

import repmp3.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseALrcFile(ALrcFile node);
    void caseAMetaLine(AMetaLine node);
    void caseALyricLine(ALyricLine node);

    void caseTTimeTag(TTimeTag node);
    void caseTMetaTag(TMetaTag node);
    void caseTEolTok(TEolTok node);
    void caseTBlank(TBlank node);
    void caseTText(TText node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
