/* This file was generated by SableCC (http://www.sablecc.org/). */

package repmp3.parser;

import repmp3.node.*;
import repmp3.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTimeTag(@SuppressWarnings("unused") TTimeTag node)
    {
        this.index = 0;
    }

    @Override
    public void caseTMetaTag(@SuppressWarnings("unused") TMetaTag node)
    {
        this.index = 1;
    }

    @Override
    public void caseTText(@SuppressWarnings("unused") TText node)
    {
        this.index = 2;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 3;
    }
}
