/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea2.analysis;

import java.util.*;
import tarea2.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPLrcFile().apply(this);
        outStart(node);
    }

    public void inALrcFile(ALrcFile node)
    {
        defaultIn(node);
    }

    public void outALrcFile(ALrcFile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALrcFile(ALrcFile node)
    {
        inALrcFile(node);
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        outALrcFile(node);
    }

    public void inAMetaLine(AMetaLine node)
    {
        defaultIn(node);
    }

    public void outAMetaLine(AMetaLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetaLine(AMetaLine node)
    {
        inAMetaLine(node);
        if(node.getMetaTag() != null)
        {
            node.getMetaTag().apply(this);
        }
        outAMetaLine(node);
    }

    public void inALyricLine(ALyricLine node)
    {
        defaultIn(node);
    }

    public void outALyricLine(ALyricLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALyricLine(ALyricLine node)
    {
        inALyricLine(node);
        if(node.getText() != null)
        {
            node.getText().apply(this);
        }
        if(node.getTimeTag() != null)
        {
            node.getTimeTag().apply(this);
        }
        outALyricLine(node);
    }
}
